Unzipping images.....
Traceback (most recent call last):
  File "/home/beria/Documents/Hackathons/crop-disease-detection/main.py", line 53, in <module>
    main()
  File "/home/beria/Documents/Hackathons/crop-disease-detection/main.py", line 32, in main
    dataset_initializer = DatasetInitializer()
                          ^^^^^^^^^^^^^^^^^^^^
  File "/home/beria/Documents/Hackathons/crop-disease-detection/src/dataset.py", line 15, in __init__
    self._unzip_images()
  File "/home/beria/Documents/Hackathons/crop-disease-detection/src/dataset.py", line 46, in _unzip_images
    shutil.unpack_archive(self.DATA_DIR+'/images.zip', 'images')
  File "/home/beria/miniconda3/lib/python3.12/shutil.py", line 1351, in unpack_archive
    func(filename, extract_dir, **kwargs)
  File "/home/beria/miniconda3/lib/python3.12/shutil.py", line 1238, in _unpack_zipfile
    raise ReadError("%s is not a zip file" % filename)
shutil.ReadError: data/images.zip is not a zip file
